function str_4x1= str_mult_4x1 (a, b)
%multiplies and stores in 4 strings the 4 rows of a 4x1 matrix that result from multiplying a 4x4 matrix 
%(a) by a 4x1 matrix (b).  (Output used as string formatted input to L-M optimization function)


str_4x1.str(1,1).str= strcat('(', a.str(1,1).str, '*', b.str(1,1).str, '+',...
                               a.str(1,2).str, '*', b.str(2,1).str, '+',...                           
                               a.str(1,3).str, '*', b.str(3,1).str, '+',...
                               a.str(1,4).str, '*', b.str(4,1).str, ')');  

str_4x1.str(2,1).str= strcat('(', a.str(2,1).str, '*', b.str(1,1).str, '+',...
                               a.str(2,2).str, '*', b.str(2,1).str, '+',...                           
                               a.str(2,3).str, '*', b.str(3,1).str, '+',...
                               a.str(2,4).str, '*', b.str(4,1).str, ')');  

                               
str_4x1.str(3,1).str= strcat('(', a.str(3,1).str, '*', b.str(1,1).str, '+',...
                               a.str(3,2).str, '*', b.str(2,1).str, '+',...                           
                               a.str(3,3).str, '*', b.str(3,1).str, '+',...
                               a.str(3,4).str, '*', b.str(4,1).str, ')');  

str_4x1.str(4,1).str= strcat('(', a.str(4,1).str, '*', b.str(1,1).str, '+',...
                               a.str(4,2).str, '*', b.str(2,1).str, '+',...                           
                               a.str(4,3).str, '*', b.str(3,1).str, '+',...
                               a.str(4,4).str, '*', b.str(4,1).str, ')');  
